// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace home_dashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626155556_FixIdType")]
    partial class FixIdType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HomeDashboard.Models.MoistureReading", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MoisturePercent")
                        .HasColumnType("int");

                    b.Property<int>("MoistureRaw")
                        .HasColumnType("int");

                    b.Property<string>("PlantId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("MoistureReadings");
                });

            modelBuilder.Entity("Plant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MoistureThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Plant");
                });

            modelBuilder.Entity("HomeDashboard.Models.MoistureReading", b =>
                {
                    b.HasOne("Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId");

                    b.Navigation("Plant");
                });
#pragma warning restore 612, 618
        }
    }
}
